# Generated by Django 6.0.1 on 2026-03-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="timezone",
            field=models.CharField(default="Europe/Lisbon", max_length=50),
        ),
    ]
