# Generated by Django 6.0.1 on 2026-04-06 21:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_timezone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="timezone",
        ),
    ]
