# Generated by Django 6.0.1 on 2026-04-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_customuser_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="timezone",
            field=models.CharField(default="Europe/Lisbon", max_length=50),
        ),
    ]
